const $ = (id: string): HTMLElement => document.getElementById(id)!;

export const K = {
  els: {
    projectName: $("projectName"), projectPath: $("projectPath"), pickProject: $("pickProject"), manualProject: $("manualProject"),
    backendStatus: $("backendStatus"), sessions: $("sessions"), newSession: $("newSession"), emptyNewSession: $("emptyNewSession"),
    emptyPickProject: $("emptyPickProject"), emptyState: $("emptyState"), conversation: $("conversation"), sessionTitle: $("sessionTitle"),
    sessionMeta: $("sessionMeta"), agentSelect: $("agentSelect"), modelSelect: $("modelSelect"), refreshButton: $("refreshButton"),
    accountButton: $("accountButton"), prompt: $("prompt"), sendButton: $("sendButton"), errorBanner: $("errorBanner"), versionLabel: $("versionLabel"),
    pathDialog: $("pathDialog"), pathForm: $("pathForm"), pathInput: $("pathInput"),
    authDialog: $("authDialog"), authInstructions: $("authInstructions"), authCodeWrap: $("authCodeWrap"), authCode: $("authCode"),
    authCancel: $("authCancel"), authOpen: $("authOpen"), attentionDialog: $("attentionDialog"), attentionTitle: $("attentionTitle"),
    attentionBody: $("attentionBody"), attentionActions: $("attentionActions"),
  } as TLStudioElements,
  state: {
    local: null,
    sessions: [],
    session: null,
    messages: [],
    activeSessions: {},
    agents: [],
    models: [],
    providers: [],
    providerDefaults: {},
    connectedProviders: new Set(),
    eventSource: null,
    fallbackPolling: null,
    sessionPolling: null,
    sending: false,
    revision: 0,
    authController: null,
    authURL: "",
    attentionKey: "",
    attachments: [],
    hostedAuth: null,
    activeEditorPath: "",
    changes: [],
    editorTabs: [],
    filesEntries: [],
    filesLoading: false,
    filesPath: "",
    filesProject: "",
    selectedFileEntry: null,
    legacySession: false,
    preview: {},
    terminal: {},
    toolRegistry: null,
    plugins: [],
    changesLoading: false,
    sseSettling: false,
  } as TLStudioState,
} as TLStudioKernel;
